# Generated by Django 5.1.6 on 2025-03-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_address1_shippingaddress_shipping_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_address1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
